uploads = []
outputs = []

[[generated]]
id = "XNxllCCe0uMhx1CHLdDZH"
uri = "file://attached_assets/generated_images/generated_image.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OkWFKRyPTV56dKx79B0gy"
uri = "file://assets/images/persona-netanyahu.png"
type = "image"
title = "generated_image"

[[generated]]
id = "19qZR1fpz7eZaaK9yaeBc"
uri = "file://assets/images/persona-galloway.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RoOScbWzmPPMjGaDKqjQJ"
uri = "file://assets/images/persona-mcconnell.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Xni1W9Vw_o7BC-3NOKbii"
uri = "file://assets/images/persona-carville.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0bC7pjQKChC6vNn-13wyp"
uri = "file://assets/images/persona-maddow.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gj8VaICvTkV3WghmXRhri"
uri = "file://assets/images/persona-omar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0AEFpUIVCdPiTnWzKbxH1"
uri = "file://assets/images/persona-biden.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yTAMtecgCwDyykV_SB0AW"
uri = "file://assets/images/persona-rosie.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rMY1kfgkJE1oFqIY4S4BE"
uri = "file://assets/images/persona-megynkelly.png"
type = "image"
title = "generated_image"

[[generated]]
id = "qM7Tehf7bIrXfJP2qxibP"
uri = "file://assets/images/persona-pambondi.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dKw-U6GOrN6gplZNi_poq"
uri = "file://assets/images/persona-candace.png"
type = "image"
title = "generated_image"

[[generated]]
id = "r1RyxN4Wa4v7Zecwdzyzq"
uri = "file://assets/images/persona-joyreid.png"
type = "image"
title = "generated_image"

[[generated]]
id = "r9swwAfkvoprYUKOqHnIl"
uri = "file://assets/images/persona-schumer.png"
type = "image"
title = "generated_image"

[[generated]]
id = "FFjg51MyLPN7ecgsY5hkG"
uri = "file://assets/images/persona-alexjones.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_pXmepSXNKp_0RyHmX3Zh"
uri = "file://assets/images/persona-obama.png"
type = "image"
title = "generated_image"

[[generated]]
id = "C7195-cczUMkJn2s5-3of"
uri = "file://assets/images/persona-melania.png"
type = "image"
title = "generated_image"

[[generated]]
id = "in9f0GrRAKny4vUx_Is9X"
uri = "file://assets/images/persona-rfk.png"
type = "image"
title = "RFK Jr persona caricature"

[[generated]]
id = "HESSsnU73xeS5ubNmWDZq"
uri = "file://assets/images/persona-erikakirk.png"
type = "image"
title = "generated_image"

[[generated]]
id = "YxUWvM2y9-gYPgwEImvBa"
uri = "file://assets/images/persona-loomer.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Eu1DmqZODcSuVR3mnp4je"
uri = "file://assets/images/persona-leavitt.png"
type = "image"
title = "generated_image"
