import { QueryClientProvider } from "@tanstack/react-query";
import { Stack } from "expo-router";
import * as SplashScreen from "expo-splash-screen";
import React, { useEffect, useState } from "react";
import {
  View,
  Text,
  Pressable,
  Modal,
  ScrollView,
  StyleSheet,
  Platform,
} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { KeyboardProvider } from "react-native-keyboard-controller";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { queryClient } from "@/lib/query-client";
import { TokenProvider } from "@/lib/token-context";
import { StatusBar } from "expo-status-bar";
import {
  useFonts,
  PlayfairDisplay_400Regular,
  PlayfairDisplay_700Bold,
  PlayfairDisplay_900Black,
} from "@expo-google-fonts/playfair-display";
import Colors from "@/constants/colors";

const DISCLAIMER_KEY = "chatdjt_disclaimer_accepted";

SplashScreen.preventAutoHideAsync();

function DisclaimerModal({ visible, onAccept }: { visible: boolean; onAccept: () => void }) {
  return (
    <Modal visible={visible} transparent animationType="fade" statusBarTranslucent>
      <View style={disclaimerStyles.overlay}>
        <View style={disclaimerStyles.popup}>
          <ScrollView showsVerticalScrollIndicator={false}>
            <Text style={disclaimerStyles.title}>
              Welcome to Chat DJT {"\u2014"} The Parody AI Experience
            </Text>
            <Text style={disclaimerStyles.warning}>
              {"\u26A0\uFE0F"} PLEASE READ: THIS IS A PARODY
            </Text>
            <Text style={disclaimerStyles.body}>
              This app is an{" "}
              <Text style={disclaimerStyles.bold}>
                independent, AI-powered comedy and entertainment project
              </Text>
              . "Donald Trump" here is an artificial intelligence simulation.
            </Text>
            <Text style={disclaimerStyles.bodyBold}>
              By entering, you acknowledge that:
            </Text>
            <View style={disclaimerStyles.bulletList}>
              <Text style={disclaimerStyles.bullet}>
                {"\u2022"} All content, including "responses" to news and user input, is{" "}
                <Text style={disclaimerStyles.bold}>
                  generated by AI and is entirely fictional
                </Text>
                .
              </Text>
              <Text style={disclaimerStyles.bullet}>
                {"\u2022"} This app is{" "}
                <Text style={disclaimerStyles.bold}>
                  NOT affiliated with, endorsed by, or connected
                </Text>{" "}
                to Donald J. Trump, his family, his business, or any political
                organization, campaign, or office.
              </Text>
              <Text style={disclaimerStyles.bullet}>
                {"\u2022"} This is a satire/parody app for entertainment purposes only.
              </Text>
            </View>
            <Pressable
              onPress={onAccept}
              style={({ pressed }) => [
                disclaimerStyles.acceptButton,
                pressed && { opacity: 0.8 },
              ]}
            >
              <Text style={disclaimerStyles.acceptButtonText}>
                I UNDERSTAND, LET ME IN
              </Text>
            </Pressable>
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
}

const disclaimerStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  popup: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 28,
    maxWidth: 500,
    width: "100%",
    maxHeight: "85%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
    color: "#1A1A1A",
    marginBottom: 14,
    lineHeight: 26,
  },
  warning: {
    fontSize: 15,
    fontWeight: "700",
    color: "#CC0000",
    textAlign: "center",
    marginBottom: 14,
  },
  body: {
    fontSize: 14,
    color: "#333",
    lineHeight: 21,
    marginBottom: 12,
    textAlign: "center",
  },
  bodyBold: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 10,
    textAlign: "center",
  },
  bold: {
    fontWeight: "700",
  },
  bulletList: {
    marginBottom: 18,
    paddingHorizontal: 4,
  },
  bullet: {
    fontSize: 13,
    color: "#333",
    lineHeight: 20,
    marginBottom: 8,
  },
  acceptButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 16,
    paddingHorizontal: 30,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 4,
  },
  acceptButtonText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
});

function RootLayoutNav() {
  return (
    <Stack
      screenOptions={{
        headerShown: false,
        contentStyle: { backgroundColor: Colors.background },
        animation: "slide_from_right",
      }}
    >
      <Stack.Screen name="index" />
      <Stack.Screen name="chat/[id]" />
      <Stack.Screen
        name="subscribe"
        options={{ presentation: "modal", animation: "slide_from_bottom" }}
      />
      <Stack.Screen
        name="cabinet"
        options={{ presentation: "modal", animation: "slide_from_bottom" }}
      />
      <Stack.Screen
        name="admin"
        options={{ presentation: "modal", animation: "slide_from_bottom" }}
      />
    </Stack>
  );
}

export default function RootLayout() {
  const [fontsLoaded, fontError] = useFonts({
    PlayfairDisplay_400Regular,
    PlayfairDisplay_700Bold,
    PlayfairDisplay_900Black,
  });
  const [disclaimerVisible, setDisclaimerVisible] = useState(false);
  const [disclaimerChecked, setDisclaimerChecked] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(DISCLAIMER_KEY).then((val) => {
      if (val !== "true") {
        setDisclaimerVisible(true);
      }
      setDisclaimerChecked(true);
    });
  }, []);

  useEffect(() => {
    if ((fontsLoaded || fontError) && disclaimerChecked) {
      SplashScreen.hideAsync();
    }
  }, [fontsLoaded, fontError, disclaimerChecked]);

  if (!fontsLoaded && !fontError) return null;

  function handleAcceptDisclaimer() {
    AsyncStorage.setItem(DISCLAIMER_KEY, "true");
    setDisclaimerVisible(false);
  }

  return (
    <ErrorBoundary>
      <QueryClientProvider client={queryClient}>
        <TokenProvider>
          <GestureHandlerRootView style={{ flex: 1 }}>
            <KeyboardProvider>
              <StatusBar style="light" />
              <DisclaimerModal
                visible={disclaimerVisible}
                onAccept={handleAcceptDisclaimer}
              />
              <RootLayoutNav />
            </KeyboardProvider>
          </GestureHandlerRootView>
        </TokenProvider>
      </QueryClientProvider>
    </ErrorBoundary>
  );
}
