// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/arena-flow/CurrentEntry.tsx": () => import("../components/mockups/arena-flow/CurrentEntry.tsx"),
  "./components/mockups/arena-flow/CurrentPaywall.tsx": () => import("../components/mockups/arena-flow/CurrentPaywall.tsx"),
  "./components/mockups/arena-flow/CurrentSetup.tsx": () => import("../components/mockups/arena-flow/CurrentSetup.tsx"),
  "./components/mockups/arena-flow/ProposedEntry.tsx": () => import("../components/mockups/arena-flow/ProposedEntry.tsx"),
  "./components/mockups/arena-flow/ProposedPaywall.tsx": () => import("../components/mockups/arena-flow/ProposedPaywall.tsx"),
  "./components/mockups/arena-flow/ProposedSetup.tsx": () => import("../components/mockups/arena-flow/ProposedSetup.tsx")
};
